project_id = "fhegpeffzyfclrvcprte"

[functions.register-panel]
verify_jwt = false

[functions.voicera-interest]
verify_jwt = false

[functions.initiate-call]
verify_jwt = false

[functions.ai4i-chat]
verify_jwt = false

[functions.ai4i-inquiry]
verify_jwt = false